[package]
name = "ebs-autoscale-rust"
version = "0.1.0"
edition = "2021"
description = "AWS EBS autoscaler written in Rust"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "ebs-autoscale-rust"

[dependencies]
aws-sdk-ec2 = "1.42.0"

[dev-dependencies]
cargo-deb = "2.2.0"
